### ISSUE TITLE
Discrepancy between sample identifier format and real identifier

### ISSUE THREAD

**Issue by simonlamb** [code4lib/ruby-oai#38]
Within  OAI::Provider::Response::Identify, the sample identifier is set as...

`r.sampleIdentifier "#{provider.prefix}:#{provider.identifier}"`

Which will result in a sample in the form of  "oai:test.edu:123"

Within  OAI::Provider::Response::RecordResponse the identifier is formatted with the following code:-

```
def identifier_for(record)
  "#{provider.prefix}/#{record.id}"
end
```

This results in the format  "oai:test.edu/123" 

The easiest (and the one less likely to cause issues for existing users) is to change the Identify class to use:-

`r.sampleIdentifier "#{provider.prefix}/#{provider.identifier}"` 

This will accurately reflect a real identifier format returned by the service.

**Comment by jrochkind** [comment]
Closing as obsolete/non-applicable.

**Comment by jrochkind** [comment]
Actually re-opening, I think this is a real problem, at least with the ActiveRecordWrapper. 

Identifiers are coming back as `prefix/id`, which I think is wrong, looking at the oai-pmh spec, I think it should be `prefix:id`, matching the sample. 

That is, I believe `:` is right, and `/` is wrong. But it's unclear if changing this will be a backwards breaking change.

**Comment by jrochkind** [comment]
## Summary of issue:

The gem is constructing identifiers as `[namespace]/[prefix]`.  But is construting a sample record in `Identify` as `[namespace]:[prefix]`. (colon instead of slash). 

[OAI guidance](http://www.openarchives.org/OAI/2.0/guidelines-oai-identifier.htm) suggests the colon, but it is not a requirement just a suggestion. 

But they should both match in this gem. I am inclined to switch it to colon to be in conformance with Guidance, even though that's technically a backwards-breaking change. 

I think the change may not affect users of `blacklight_oai_provider`, as it overrides the relevant methods anyway (to use colon).  In fact, it overrides them in a [monkey-patch file](https://github.com/projectblacklight/blacklight_oai_provider/blob/f4b25ee43846cb9efc9d5124a8639a496153aa18/config/initializers/oai_patches.rb) whose commit says "Patch identifier bug in OAI gem", so apparently they considered it a bug -- yep, we should just fix it here.
